language: crystal

script:
  - crystal spec
  - crystal tool format --check
  - crystal docs
deploy:
  provider: pages
  cleanup: false
  github_token: $GITHUB_TOKEN
  project_name: rope
  on:
    branch: master
  local_dir: docs
